<Project Sdk="ricaun.Revit.Sdk/1.0.0">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <TargetFrameworks>2027;2026;2025;2024;2023;2022;2021;2020;2019</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NUnit" Version="3.13.3" />
    <PackageReference Include="NUnit3TestAdapter" Version="3.16.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RevitAddin.CommandLoader\RevitAddin.CommandLoader.csproj" />
  </ItemGroup>

  <!-- Revit 2021-2024 -->
  <ItemGroup Condition="$(RevitVersion) &gt;= '2021' AND $(RevitVersion) &lt;= '2024'">
    <PackageReference Include="Microsoft.CodeDom.Providers.DotNetCompilerPlatform" Version="4.1.0" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="9.*">
      <NoWarn>NU1903</NoWarn>
    </PackageReference>
  </ItemGroup>

</Project>
